name: Deploy App AWS

on:
  push:
    branches:
      - main
      - dev
      - gui

env:
  AWS_ID: 435238036812  
  AWS_REGION: us-east-1
  CLUSTER_NAME: eks-stage-cluster
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure Docker for ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push Docker Image
        working-directory: frontend
        run: |
          docker build -t $AWS_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:${{ github.sha }} .
          docker push $AWS_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:${{ github.sha }}

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/frontend frontend=$AWS_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:${{ github.sha }}
