name: Infra AWS

on:
  workflow_dispatch: # Rodar manualmente

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra/aws

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/aws
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/aws
